name: Deploy

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: self-hosted
    if: contains(github.event.head_commit.message, '[deploy]') # Optional: filter by commit message
    steps:
      - name: Set environment variables
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          echo "Removing previous containers..."
          docker ps -a --filter "name=logistics-container" --format "{{.ID}}" | xargs -r docker rm -f

          echo "Setting up dotenv file..."
          cd backend
          echo "MONGO_URI=${MONGO_URI}" >> .env
          echo "JWT_SECRET=${JWT_SECRET}" >> .env
          cd ..

          echo "Building Docker image..."
          docker build -t logistics .

          echo "Running container..."
          docker run -d --name logistics-container -p 3012:3012 -p 3069:3069 logistics

          echo "Deployment complete!"
